[workspace]
resolver = "2"
members = ["utils_lib", "adblog_src", "apkex_src", "apkinfo_src"]
# default-members = ["apk_utils"]

exclude = []

[workspace.package]
publish = false
edition = "2021"
rust-version = "1.78"

[workspace.dependencies]
utils_lib = { path = "./utils_lib" }
adblog_src = { path = "./adblog_src" }
apkex_src = { path = "./apkex_src" }
apkinfo_src = { path = "./apkinfo_src" }

clap = { version = "4.5.21", features = ["derive"] }
anyhow = "1.0.93"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.215", features = ["derive"] }

serde_json = "1.0.133"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "registry",
    "time",
] }
tracing-appender = "0.2.3"
time = { version = "0.3.36", features = ["local-offset"] }
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
zip = { version = "5.1.1", features = ["deflate"] }
